### ISSUE TITLE
Cannot call method 'startSystemMove' of undefined

### ISSUE THREAD

**Issue by prateekmedia** [cutefishos/videoplayer#1]
https://github.com/cutefishos/videoplayer/blob/176a8932ce4507e6bc92ef9da29fb2510fc3cd5f/src/qml/MpvVideo.qml#L209

**Comment by reionwong** [comment]
Try installing the latest https://github.com/cutefishos/fishui

**Comment by prateekmedia** [comment]
> Try installing the latest https://github.com/cutefishos/fishui

Ok I think the latest is not updated on manjaro repositories, anyways thanks.
