### ISSUE TITLE
Add Arch and manjaro packages for cutefishos videoplayer

### ISSUE THREAD

**Issue by prateekmedia** [cutefishos/videoplayer#2]
Currently the only way to install this is to build from source. It would be good if it will be available on arch and manjaro repositories with other cutefish packages.

**Comment by SwampRabbit** [comment]
its in AUR https://aur.archlinux.org/packages/cutefish-videoplayer-git
This sounds like a Arch package maintainer issue, not a CutefishOS issue

**Comment by prateekmedia** [comment]
No cutefish have official packages for every other package except this.

Also this is not included in the testing Debian iso as far as I remember.

**Comment by SwampRabbit** [comment]
@prateekmedia yeah it looks like Felix Yan did a bunch back in August, my bad.

Its probably just a matter of time and getting these applications to a decent state, it looks like they have enough going on for sure.
I read an article on Cutefish OS and saw they needed some of their Debian packaging updated some, I haven't even tried the Beta.  :P
